# Generated by Django 3.0.4 on 2020-03-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('in_quarantine', models.BooleanField(default=True)),
                ('is_tested_positive', models.BooleanField(default=False)),
                ('is_hospitalized', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('is_recovered', models.BooleanField(default=False)),
                ('symptoms_gravity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('SEVERE', 'Severe')], max_length=32, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
